### PR TITLE
fix: look beyond first page of repo workflows

### LINKED ISSUE #198: Only looks at the first 30 workflows found in the repository
By default, calling `octokit.rest.actions.listRepoWorkflows` without `per_page` will return the first 30 workflows found in the repository. It is an issue in our case since we have a long list of workflows to trigger all kind of deployments and the one I wanted to use was not found by the `return-dispatch` action because it was only in the second page of results.

### PR DESCRIPTION
**Pull request by pmrotule**
Closes #198

I hope you'll like my solution! I tested it already and it fixed the issue in our case where the workflow was found in the second page of results.

### CODE REVIEW

**Comment by Codex-** [comment]
Thanks for submitting this PR!

Octokit actually provides a way to iterate over pages, we should probably adopt that method, an example is here:
https://github.com/Codex-/knip-reporter/blob/main/src/api.ts#L51

**Comment by pmrotule** [comment]
> Thanks for submitting this PR!
> 
> Octokit actually provides a way to iterate over pages, we should probably adopt that method, an example is here: https://github.com/Codex-/knip-reporter/blob/main/src/api.ts#L51

Great stuff! I wasn't aware of it. I'll quickly make the change.

**Comment by Codex-** [comment]
Tests failing, the tests can be tricky, if you're happy to wait I can try address them on Friday or you can see how I handled testing against this in the knip-reporter repository and update the tests

**Comment by pmrotule** [comment]
> Tests failing, the tests can be tricky, if you're happy to wait I can try address them on Friday or you can see how I handled testing against this in the knip-reporter repository and update the tests

Should be good now. There was also an issue with the token so I assumed it's because I'm the one who pushed the commit and I don't have the right access. I didn't push the update on the bundle this time. Feel free to take it from there.

**Review by Codex- — APPROVED** [review]
Thank you so much for your work on this, hugely appreciated

**Comment by pmrotule** [comment]
@Codex- Just so you know, it seems like the `v1` tag was not yet updated to the latest version [1.12.0](https://github.com/Codex-/return-dispatch/releases/tag/v1.12.0).

**Comment by Codex-** [comment]
Ah I see, it rejected when I did it originally, fixed now! Thanks for pointing that out @pmrotule

**Pull request merged**
